version: "3.8"
services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./:/web
    ports:
      - "3001:3000"
    networks:
      - opnmint-backend_backend-network

networks:
  opnmint-backend_backend-network:
    external: true
